//
// Created by glumes on 2021/3/7.
//

#ifndef VULKANCAMERA_FILTERTYPE_H
#define VULKANCAMERA_FILTERTYPE_H


enum FilterType{
    SHOW_TYPE,
    RBG_FILTER_TYPE,
    MIRROR_FILTER_TYPE,
    REVERT_FILTER_TYPE,
    EXPOSURE_FILTER_TYPE,
    GAMMA_FILTER_TYPE,
    CONTRAST_FILTER_TYPE,
    HAZE_FILTER_TYPE,
};
#endif //VULKANCAMERA_FILTERTYPE_H
